nameOverride: ""
fullnameOverride: ""

image:
  repository: quay.io/prometheus-operator/prometheus-operator
  pullPolicy: IfNotPresent
  tag: ""
  digest: ""

resources: { }
#  limits:
#    cpu: 200m
#    memory: 200Mi
#  requests:
#    cpu: 100m
#    memory: 100Mi

livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

securityContext:
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}
#  kubernetes.io/os: linux

serviceMonitor:
  enabled: true

# ---------------------------------------------------------
# Config reloader
# ---------------------------------------------------------
configReloader:
  image:
    repository: quay.io/prometheus-operator/prometheus-config-reloader
    pullPolicy: IfNotPresent
    tag: ""
    digest: ""

#  resources:
#      limits:
#        cpu: 10m
#        memory: 50Mi
#      requests:
#        cpu: 10m
#        memory: 50Mi
