apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
automountServiceAccountToken: true
