apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  version: {{ printf "v%s" .Chart.AppVersion }}
  replicas: {{ .Values.replicas }}
  serviceAccountName: {{ include "prometheus.fullname" . }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.securityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
  {{- end }}
  {{/* Prometheus config */}}
  {{- if .Values.alertmanager.enabled }}
  alerting:
    alertmanagers:
      - apiVersion: {{ .Values.alertmanager.apiVersion }}
        name: {{ .Values.alertmanager.name }}
        namespace: {{ default .Values.alertmanager.namespace .Release.Namespace }}
        port: {{ .Values.alertmanager.port }}
  {{- end }}
  {{- if .Values.spec.externalUrl }}
  externalUrl: {{ .Values.spec.externalUrl | quote }}
  {{- end }}
  {{- if .Values.spec.retention }}
  retention: {{ .Values.spec.retention | quote }}
  {{- end }}
  {{- if .Values.spec.retentionSize }}
  retentionSize: {{ .Values.spec.retentionSize | quote }}
  {{- end }}
  podMonitorNamespaceSelector:
    {{- toYaml .Values.spec.podMonitorNamespaceSelector | nindent 4 }}
  podMonitorSelector:
    {{- toYaml .Values.spec.podMonitorSelector | nindent 4 }}
  probeNamespaceSelector:
    {{- toYaml .Values.spec.probeNamespaceSelector | nindent 4 }}
  probeSelector:
    {{- toYaml .Values.spec.probeSelector | nindent 4 }}
  ruleNamespaceSelector:
    {{- toYaml .Values.spec.ruleNamespaceSelector | nindent 4 }}
  ruleSelector:
    {{- toYaml .Values.spec.ruleSelector | nindent 4 }}
  scrapeConfigNamespaceSelector:
    {{- toYaml .Values.spec.scrapeConfigNamespaceSelector | nindent 4 }}
  scrapeConfigSelector:
    {{- toYaml .Values.spec.scrapeConfigSelector | nindent 4 }}
  serviceMonitorNamespaceSelector:
    {{- toYaml .Values.spec.serviceMonitorNamespaceSelector | nindent 4 }}
  serviceMonitorSelector:
    {{- toYaml .Values.spec.serviceMonitorSelector | nindent 4 }}
