apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  ports:
  - name: web
    port: {{ .ports.web }}
    protocol: TCP
    targetPort: web
    {{- if (and (eq .type "NodePort") .nodePorts.web ) }}
    nodePort: {{ .nodePorts.web }}
    {{- end }}
  - name: reloader-web
    port: {{ .ports.reloaderWeb }}
    protocol: TCP
    targetPort: reloader-web
    {{- if (and (eq .type "NodePort") .nodePorts.reloaderWeb ) }}
    nodePort: {{ .nodePorts.reloaderWeb }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "prometheus.podSelectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
