{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: web
  - port: reloader-web
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
  {{- end }}
