apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    {{- include "prometheus-operator.selectorLabels" . | nindent 4 }}
