apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
type: Opaque
data:
  alertmanager.yaml: {{ toYaml .Values.config | b64enc | quote }}
  {{- range $key, $val := .Values.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
