apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  ports:
    - name: web
      port: 9093
      protocol: TCP
      {{- if (and (eq .type "NodePort") .nodePorts.web ) }}
      nodePort: {{ .nodePorts.web }}
      {{- end }}
    - name: reloader-web
      port: {{ .ports.reloaderWeb }}
      protocol: TCP
      targetPort: reloader-web
      {{- if (and (eq .type "NodePort") .nodePorts.reloaderWeb ) }}
      nodePort: {{ .nodePorts.reloaderWeb }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "alertmanager.podSelectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
