apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
automountServiceAccountToken: false
