{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      {{- include "prometheus-operator.selectorLabels" . | nindent 6 }}
  {{- end }}
