apiVersion: v2
name: monitoring-stack
description: Hauki Tech Monitoring Stack
type: application
version: 0.1.0

dependencies:
  - name: haukitech/prometheus-operator
    version: '*'
    condition: dependencies.prometheusOperator

  - name: haukitech/prometheus
    version: '*'
    condition: dependencies.prometheus
