apiVersion: v2
name: monitoring-stack
description: Hauki Tech Monitoring Stack
type: application
version: 0.1.0

dependencies:
  - name: prometheus-operator
    version: '*'
    repository: https://haukitech.github.io/helm-charts/
    condition: dependencies.prometheusOperator

  - name: prometheus
    version: '*'
    repository: https://haukitech.github.io/helm-charts/
    condition: dependencies.prometheus
