dependencies:
  prometheusOperator: true
  prometheus: true
  alertmanager: true
  kubeStateMetrics: true

prometheus-operator:
  fullnameOverride: prometheus-operator

prometheus:
  fullnameOverride: prometheus

alertmanager:
  fullnameOverride: alertmanager

kube-state-metrics:
  fullnameOverride: kube-state-metrics
  prometheus:
    monitor:
      enabled: true
      honorLabels: true
      relabelings:
        - action: labeldrop
          regex: (pod|service|endpoint|namespace)
